name: patrulha_xx
description: patrulhaXX - Navegação privada e segura.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # InAppWebView — navegador completo (NÃO webview_flutter)
  flutter_inappwebview: ^6.1.5

  # SVG
  flutter_svg: ^2.0.10+1

  # Armazenamento seguro criptografado (invisível para outros apps)
  flutter_secure_storage: ^9.2.2

  # Caminhos de diretório privado do app
  path_provider: ^2.1.4

  # HTTP requests
  http: ^1.2.2

  # Download de ficheiros (vídeos/imagens apenas dentro do app)
  dio: ^5.4.3+1

  # Permissões runtime
  permission_handler: ^11.3.1

  # Ionicons
  ionicons: ^0.2.2

  # Cache de imagens de rede (favicons)
  cached_network_image: ^3.3.1

  # Extração de cor dominante do favicon
  palette_generator: ^0.3.3+3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app1.png   # Ícone local PornHub
    - assets/images/background.png  # Imagem de fundo (1080x1920px)
